export const categories = [
    "All",
    "React",
    "Gaming",
    "Coding",
    "Next.js",
    "Cat memes",
    "Dog videos",
    "LoFi Music",
    "Programming",
    "Procreate Art",
    "Classical music",
    "Game Development",
    "Impractical Jokes",
    "Hollywood movie trailor",
    "Blender 3D art challenges",
]